### ISSUE TITLE
`writeFiles` fails when target file is under a directory that doesn't exist

### ISSUE THREAD

**Issue by ykrasik** [maxmilton/esbuild-minify-templates#92]
Hi, great lib!

There's an issue where `writeFiles` will fail if the directory of the output file doesn't exist. 
For example, if `buildResult.outputFiles.path`=`src/index.js`, and `src` doesn't exist, it will fail at runtime.

The solution is to call `fs.promises.mkdir(..., { recursive: true })` before writing the files.

**Comment by maxmilton** [comment]
Thanks for bringing this up!

For some reason I was under the impression that esbuild throws an error when the output directory doesn't exist so I was matching that behaviour... but a quick experiment proved me wrong! Builds using esbuild CLI and programmatically both create the output directories as needed.

Added a fix for this. I've got a few other things I'd like changed so once those are in I'll create a new release.

**Comment by ykrasik** [comment]
Awesome, thank you!
